Update README to provide more clear examples
pytest-dev/pytest-localserver pull request #105
Opened 2024-12-04 03:24 UTC by alissa-huskey

I updated the `README` with some of my own code examples and did a little cleanup/polish.

* Replace "Quickstart" section with the code for the simplest possible use-case.
* Replace `WSGI` example, as I wasn't able to get the previous example working.
* Rename the previous "Quickstart" section to "How-To".
* Rename "Available funcargs" section to "Fixtures". (That seems to be the more common term. In any case, I didn't previously know that "funcargs" was another term for "fixtures", so it may be more clear to others as well.)
* Use `code` directives instead of literal blocks to syntax highlight python code.

2025-01-29 07:14 UTC, diazona commented
Hi @alissa-huskey, thanks for sending a contribution! I'm sorry to keep you waiting; I haven't been active on GitHub for a little while (because real life got busy) and I didn't see the notification about your PR.

If you don't mind waiting a bit longer, I'd like to come back to this and review it over the weekend when I can give it my full attention.

2025-02-02 06:25 UTC, diazona requested changes
Thanks again! These changes mostly look good, I just made a few suggestions.

Sorry again for the delayed response; I'll try to keep checking back so I don't miss further activity here.

2025-02-02 18:14 UTC, alissa-huskey commented on README.rst
> +locally! :
Ah, right. I missed that one when changing `::` to `.. code::`.

2025-02-02 18:27 UTC, alissa-huskey commented
No worries about the delay! Real life happens. I tend to be on github in fits and starts anyway, so I never expect a prompt response, if any.

I believe I addressed all of your feedback. Additionally I changed the monkeypatch link to point to the stable pytest.org docs URL.

2025-02-03 09:09 UTC, diazona approved these changes
Good call on that monkeypatch change.

Thanks again; I appreciate both the contribution and your patience!

2025-02-03 09:29 UTC, merged