Remove redudant `wheel` dep from `pyproject.toml`
pytest-dev/pytest-localserver pull request #34
Opened 2022-05-06 08:05 UTC by mgorny

The `setuptools` PEP517 backend provides the dependency on `wheel`
implicitly.  The explicit dep is unnecessary and specifying it is
no longer the recommended practice per setuptools documentation.

2022-05-06 08:35 UTC, diazona commented
pypa/setuptools#3056 for context

Thanks for the fix! I want to give it a little while (probably a few days) in case the other maintainers have any comments, then I'll merge this.

2022-05-06 08:45 UTC, RonnyPfannschmidt requested changes

2022-05-06 08:45 UTC, RonnyPfannschmidt commented on pyproject.toml
> +requires = ["setuptools >=42", "setuptools_scm[toml] >=3.4.1"]
i suspect a version pin increase for setuptools is also necessary, can we crosscheck

2022-05-06 08:51 UTC, RonnyPfannschmidt approved these changes
its been there from day on, so YAY

2022-05-09 00:18 UTC, merged

2022-05-09 07:50 UTC, mgorny commented
Thanks!